"""add_implementation_tables

Revision ID: 44dad75b8d13
Revises: 
Create Date: 2026-08-15 12:19:46.548076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44dad75b8d13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('github_access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_url'), 'repositories', ['url'], unique=True)
    op.create_table('task_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_statuses_id'), 'task_statuses', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('implementations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_requirement', sa.Text(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('worktree_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PREPARING', 'PLANNING', 'NEEDS_CONTEXT', 'READY', 'RUNNING', 'VERIFYING', 'REPAIRING', 'VERIFIED', 'FAILED', 'PR_CREATED', name='implementation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implementations_repository_id'), 'implementations', ['repository_id'], unique=False)
    op.create_index(op.f('ix_implementations_status'), 'implementations', ['status'], unique=False)
    op.create_index(op.f('ix_implementations_user_id'), 'implementations', ['user_id'], unique=False)
    op.create_table('analysis_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('blob_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_artifacts_id'), 'analysis_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_artifacts_type'), 'analysis_artifacts', ['type'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capability_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_analysis_id'), 'capabilities', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_capabilities_id'), 'capabilities', ['id'], unique=False)
    op.create_index(op.f('ix_capabilities_name'), 'capabilities', ['name'], unique=False)
    op.create_table('database_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_objects_analysis_id'), 'database_objects', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_database_objects_id'), 'database_objects', ['id'], unique=False)
    op.create_index(op.f('ix_database_objects_name'), 'database_objects', ['name'], unique=False)
    op.create_index(op.f('ix_database_objects_object_type'), 'database_objects', ['object_type'], unique=False)
    op.create_index(op.f('ix_database_objects_symbol_id'), 'database_objects', ['symbol_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(), nullable=False),
    sa.Column('symbol_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_analysis_id'), 'evidence', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_evidence_fact_type'), 'evidence', ['fact_type'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_symbol_id'), 'evidence', ['symbol_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_analysis_id'), 'files', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.create_table('implementation_contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('implementation_id', sa.String(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('affected_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tests_required', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('security_considerations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implementation_contracts_implementation_id'), 'implementation_contracts', ['implementation_id'], unique=True)
    op.create_table('implementation_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('implementation_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('affected_symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('component_type', sa.Enum('EXISTING', 'NEW', name='component_type'), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expected_changes', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='plan_step_status'), nullable=False),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implementation_plans_implementation_id'), 'implementation_plans', ['implementation_id'], unique=False)
    op.create_index(op.f('ix_implementation_plans_status'), 'implementation_plans', ['status'], unique=False)
    op.create_index(op.f('ix_implementation_plans_step_number'), 'implementation_plans', ['step_number'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('from_symbol_id', sa.String(), nullable=False),
    sa.Column('to_symbol_id', sa.String(), nullable=False),
    sa.Column('rel_type', sa.String(), nullable=False),
    sa.Column('evidence_line', sa.Integer(), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_analysis_id'), 'relationships', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_relationships_from_symbol_id'), 'relationships', ['from_symbol_id'], unique=False)
    op.create_index(op.f('ix_relationships_id'), 'relationships', ['id'], unique=False)
    op.create_index(op.f('ix_relationships_rel_type'), 'relationships', ['rel_type'], unique=False)
    op.create_index(op.f('ix_relationships_to_symbol_id'), 'relationships', ['to_symbol_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('handler_symbol_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_analysis_id'), 'routes', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_routes_handler_symbol_id'), 'routes', ['handler_symbol_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_path'), 'routes', ['path'], unique=False)
    op.create_index(op.f('ix_routes_symbol_id'), 'routes', ['symbol_id'], unique=False)
    op.create_table('capability_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('symbol_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_members_capability_id'), 'capability_members', ['capability_id'], unique=False)
    op.create_index(op.f('ix_capability_members_evidence_id'), 'capability_members', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_capability_members_id'), 'capability_members', ['id'], unique=False)
    op.create_index(op.f('ix_capability_members_symbol_id'), 'capability_members', ['symbol_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qualified_name', sa.String(), nullable=True),
    sa.Column('symbol_type', sa.String(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_analysis_id'), 'symbols', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_symbols_file_id'), 'symbols', ['file_id'], unique=False)
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=False)
    op.create_index(op.f('ix_symbols_qualified_name'), 'symbols', ['qualified_name'], unique=False)
    op.create_index(op.f('ix_symbols_symbol_type'), 'symbols', ['symbol_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_symbol_type'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_qualified_name'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_file_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_analysis_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_capability_members_symbol_id'), table_name='capability_members')
    op.drop_index(op.f('ix_capability_members_id'), table_name='capability_members')
    op.drop_index(op.f('ix_capability_members_evidence_id'), table_name='capability_members')
    op.drop_index(op.f('ix_capability_members_capability_id'), table_name='capability_members')
    op.drop_table('capability_members')
    op.drop_index(op.f('ix_routes_symbol_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_path'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_handler_symbol_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_analysis_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_relationships_to_symbol_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_rel_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_symbol_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_analysis_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_implementation_plans_step_number'), table_name='implementation_plans')
    op.drop_index(op.f('ix_implementation_plans_status'), table_name='implementation_plans')
    op.drop_index(op.f('ix_implementation_plans_implementation_id'), table_name='implementation_plans')
    op.drop_table('implementation_plans')
    op.drop_index(op.f('ix_implementation_contracts_implementation_id'), table_name='implementation_contracts')
    op.drop_table('implementation_contracts')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_analysis_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_evidence_symbol_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_fact_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_analysis_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_database_objects_symbol_id'), table_name='database_objects')
    op.drop_index(op.f('ix_database_objects_object_type'), table_name='database_objects')
    op.drop_index(op.f('ix_database_objects_name'), table_name='database_objects')
    op.drop_index(op.f('ix_database_objects_id'), table_name='database_objects')
    op.drop_index(op.f('ix_database_objects_analysis_id'), table_name='database_objects')
    op.drop_table('database_objects')
    op.drop_index(op.f('ix_capabilities_name'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_id'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_analysis_id'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_analysis_artifacts_type'), table_name='analysis_artifacts')
    op.drop_index(op.f('ix_analysis_artifacts_id'), table_name='analysis_artifacts')
    op.drop_table('analysis_artifacts')
    op.drop_index(op.f('ix_implementations_user_id'), table_name='implementations')
    op.drop_index(op.f('ix_implementations_status'), table_name='implementations')
    op.drop_index(op.f('ix_implementations_repository_id'), table_name='implementations')
    op.drop_table('implementations')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_task_statuses_id'), table_name='task_statuses')
    op.drop_table('task_statuses')
    op.drop_index(op.f('ix_repositories_url'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
