"""
Centralized event type definitions for the Engineering Agent subsystem.

This module serves as the single source of truth for SSE event names, payloads,
and contracts between backend emission and frontend handlers.
"""
from enum import Enum


class AgentEventType(str, Enum):
    """Complete registry of agent events emitted during run lifecycle."""

    # Execution Control
    STARTED = "STARTED"
    STATE_TRANSITION = "STATE_TRANSITION"
    CANCELLATION_COMPLETED = "CANCELLATION_COMPLETED"

    # Plan Lifecycle
    PLAN_READY_FOR_APPROVAL = "PLAN_READY_FOR_APPROVAL"
    PLAN_APPROVED = "PLAN_APPROVED"
    PLAN_REJECTED = "PLAN_REJECTED"

    # Task Lifecycle
    NEXT_TASK_SELECTED = "NEXT_TASK_SELECTED"
    TASK_READY = "TASK_READY"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"

    # Verification Lifecycle
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"

    # Repair Lifecycle
    REPAIR_STARTED = "REPAIR_STARTED"
    REPAIR_COMPLETED = "REPAIR_COMPLETED"
    REPAIR_REVERIFY_COMPLETED = "REPAIR_REVERIFY_COMPLETED"

    # Planning Phases
    PLANNING_STARTED = "PLANNING_STARTED"
    PLANNING_COMPLETED = "PLANNING_COMPLETED"
    PLANNING_FAILED = "PLANNING_FAILED"

    # Context Assembly
    CONTEXT_ASSEMBLY_STARTED = "CONTEXT_ASSEMBLY_STARTED"
    CONTEXT_ASSEMBLY_COMPLETED = "CONTEXT_ASSEMBLY_COMPLETED"
    CONTEXT_ASSEMBLY_FAILED = "CONTEXT_ASSEMBLY_FAILED"

    # Intent Classification
    INTENT_CLASSIFIED = "INTENT_CLASSIFIED"

    # Approval/Safety
    ACTION_APPROVAL_REQUESTED = "ACTION_APPROVAL_REQUESTED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"

    # Tool Execution
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    TOOL_CALL_BLOCKED = "TOOL_CALL_BLOCKED"

    # Agent Loop States
    AGENT_THINKING = "AGENT_THINKING"
    AGENT_TOOL_REQUESTED = "AGENT_TOOL_REQUESTED"
    AGENT_LIMIT_WARNING = "AGENT_LIMIT_WARNING"
    AGENT_COMPLETION_REQUESTED = "AGENT_COMPLETION_REQUESTED"
    AGENT_LOOP_STOPPED = "AGENT_LOOP_STOPPED"

    # Task Verification
    AGENT_TASK_READY_FOR_VERIFICATION = "AGENT_TASK_READY_FOR_VERIFICATION"

    # Misc
    AGENT_MESSAGE = "AGENT_MESSAGE"
    CONTRACT_GENERATED = "CONTRACT_GENERATED"
    CODE_GENERATING = "CODE_GENERATING"


# Events that trigger workspace snapshot refresh on frontend
SNAPSHOT_REFRESH_TRIGGERS = {
    AgentEventType.PLAN_READY_FOR_APPROVAL,
    AgentEventType.PLAN_APPROVED,
    AgentEventType.TASK_COMPLETED,
    AgentEventType.TASK_FAILED,
    AgentEventType.VERIFICATION_COMPLETED,
    AgentEventType.REPAIR_REVERIFY_COMPLETED,
}
